stages:
  - sync

pull_from_github:
  stage: sync
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  variables:
    GIT_STRATEGY: clone
    GIT_HTTP_TIMEOUT: 60
  script:
    - git config --global user.name "plantingfestival"
    - git config --global user.email "plantingfestival@126.com"
    - git remote remove github || true
    - git remote add github https://$GITHUB_USERNAME:$GITHUB_PAT@github.com/plantingfestival/KingdomRushAlliance_DragonBone.git
    - git fetch github --prune --tags --force
    - git push origin --mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"